set positional-arguments := true

ROOT := parent_directory(parent_directory(justfile_directory()))

default:
    @just --list

list:
    @just --list

doctor:
    @uv run --project {{ROOT}} --package xcron-capability-metrics-test python -c "from xcron.capabilities.metrics_test.provider import CAPABILITY; assert CAPABILITY.id == 'metrics:test'"

check:
    @uv run --project {{ROOT}} --package xcron-capability-metrics-test pytest {{ROOT}}/capabilities/xcron-capability-metrics-test/tests -q

test:
    @uv run --project {{ROOT}} --package xcron-capability-metrics-test pytest {{ROOT}}/capabilities/xcron-capability-metrics-test/tests -q

build:
    @uv build --project {{ROOT}} --package xcron-capability-metrics-test --out-dir /tmp/xcron-metrics-test-build --clear
