"""Domain models and normalization logic for xcron."""

from libs.domain.diffing import (
    DeployedJobState,
    PlanChange,
    PlanChangeKind,
    ProjectPlan,
    ProjectState,
    StatusEntry,
    StatusKind,
    build_project_plan,
    build_status_entries,
)
from libs.domain.models import (
    DEFAULT_SHELL,
    DEFAULT_WORKING_DIR,
    SUPPORTED_EVERY_SUFFIXES,
    DefaultsConfig,
    JobDefinition,
    NormalizedExecutionConfig,
    NormalizedJob,
    NormalizedManifest,
    OverlapPolicy,
    ProjectConfig,
    ProjectManifest,
    ScheduleDefinition,
    ScheduleKind,
    build_artifact_id,
    build_qualified_job_id,
)
from libs.domain.normalization import normalize_job, normalize_manifest, normalized_job_ids

__all__ = [
    "DEFAULT_SHELL",
    "DEFAULT_WORKING_DIR",
    "DeployedJobState",
    "SUPPORTED_EVERY_SUFFIXES",
    "DefaultsConfig",
    "JobDefinition",
    "NormalizedExecutionConfig",
    "NormalizedJob",
    "NormalizedManifest",
    "OverlapPolicy",
    "PlanChange",
    "PlanChangeKind",
    "ProjectPlan",
    "ProjectConfig",
    "ProjectManifest",
    "ProjectState",
    "ScheduleDefinition",
    "ScheduleKind",
    "StatusEntry",
    "StatusKind",
    "build_artifact_id",
    "build_project_plan",
    "build_status_entries",
    "build_qualified_job_id",
    "normalize_job",
    "normalize_manifest",
    "normalized_job_ids",
]
