set positional-arguments := true

ROOT := parent_directory(parent_directory(justfile_directory()))

default:
    @just --list

list:
    @just --list

doctor:
    @uv run --project {{ROOT}} python -c "from xcron.capabilities.settings_xcfg.provider import CAPABILITY; assert CAPABILITY.id == 'settings:xcfg'"

check:
    @uv run --project {{ROOT}} pytest {{ROOT}}/capabilities/xcron-capability-settings-xcfg/tests -q

test:
    @uv run --project {{ROOT}} pytest {{ROOT}}/capabilities/xcron-capability-settings-xcfg/tests -q

build:
    @uv build --project {{ROOT}} --package xcron-capability-settings-xcfg --out-dir /tmp/xcron-settings-xcfg-build --clear
