set positional-arguments := true

ROOT := parent_directory(parent_directory(justfile_directory()))

default:
    @just --list

list:
    @just --list

doctor:
    @uv run --project {{ROOT}} python -c "from xcron.capabilities.manifest_yaml.provider import CAPABILITY; assert CAPABILITY.id == 'manifest:yaml'"

check:
    @uv run --project {{ROOT}} pytest {{ROOT}}/capabilities/xcron-capability-manifest-yaml/tests -q

test:
    @uv run --project {{ROOT}} pytest {{ROOT}}/capabilities/xcron-capability-manifest-yaml/tests -q

build:
    @uv build --project {{ROOT}} --package xcron-capability-manifest-yaml --out-dir /tmp/xcron-manifest-yaml-build --clear
