"""Context-independent service layer for xcron."""
"""Reusable services for xcron actions."""

from libs.services.config_loader import (
    MANIFEST_DIR,
    MANIFEST_SUFFIXES,
    AmbiguousManifestSelectionError,
    LoadedManifestDocument,
    ManifestLoadError,
    ManifestNotFoundError,
    ManifestParseError,
    ProjectResolutionError,
    attach_parsed_manifest,
    load_project_manifest,
    resolve_manifest_path,
    resolve_project_root,
)
from libs.services.hash_service import ManifestHashes, build_manifest_hashes
from libs.services.hook_installer import (
    CODEX_CONFIG_RELATIVE_PATH,
    CODEX_HOOKS_RELATIVE_PATH,
    CLAUDE_SETTINGS_RELATIVE_PATH,
    HookInstallResult,
    HookStatusResult,
    capture_session_end,
    ensure_agent_hooks,
    inspect_agent_hooks,
    resolve_xcron_executable,
)
from libs.services.logging_paths import RuntimePaths, ensure_runtime_dirs, resolve_runtime_paths, runtime_log_paths_for_wrapper
from libs.services.manifest_editor import (
    ManifestEditError,
    ManifestEditValidationError,
    ManifestJobAlreadyExistsError,
    ManifestJobNotFoundError,
    ManifestMutationResult,
    add_manifest_job,
    get_manifest_job,
    list_manifest_jobs,
    remove_manifest_job,
    set_manifest_job_enabled,
    update_manifest_job,
)
from libs.services.observability import (
    check_output_logged,
    configure_logging,
    get_logger,
    instrument_action,
    run_logged_subprocess,
)
from libs.services.schema_validator import ValidationMessage, validate_schema, validate_semantics
from libs.services.state_store import (
    STATE_ENV_VAR,
    default_backend_for_current_platform,
    delete_project_state,
    load_project_state,
    resolve_project_state_dir,
    resolve_project_state_path,
    resolve_state_root,
    save_project_state,
)
from libs.services.axi_presenter import (
    build_error_payload,
    collapse_home_path,
    parse_fields_csv,
    render_payload,
    select_collection_fields,
    select_fields,
    select_list_fields,
    select_nested_fields,
    truncate_text,
)
from libs.services.claude_hooks import ClaudeHookStatus, ensure_claude_hooks, inspect_claude_hooks
from libs.services.cli_mappers import (
    map_apply_response,
    map_error_response,
    map_home_response,
    map_inspect_response,
    map_jobs_list_response,
    map_jobs_mutation_response,
    map_jobs_show_response,
    map_plan_response,
    map_prune_response,
    map_status_response,
    map_validation_response,
)
from libs.services.cli_responses import (
    ErrorDetail,
    ErrorResponse,
    HomeJobsSummary,
    HomeResponse,
    InspectResponse,
    JobListRow,
    JobsListResponse,
    JobsShowResponse,
    MutationResponse,
    PayloadConvertible,
    PlanChangeRow,
    PlanResponse,
    StatusResponse,
    StatusRow,
    SummaryRow,
    ValidationSummaryResponse,
)
from libs.services.cli_contracts import (
    COMMAND_CONTRACTS,
    CommandContract,
    allowed_request_fields,
    get_command_contract,
    validate_requested_fields,
)
from libs.services.codex_hooks import CodexHookStatus, ensure_codex_hooks, inspect_codex_hooks
from libs.services.help_renderer import HELP_PACKAGE, load_help_body, render_help_text
from libs.services.output_renderer import (
    render_collection_response_toon,
    render_list_response_toon,
    render_nested_response_toon,
    render_response_toon,
)
from libs.services.toon_renderer import TOON_OPTIONS, normalize_for_toon, render_toon
from libs.services.wrapper_renderer import RenderedWrapper, render_wrapper, write_wrapper

__all__ = [
    "AmbiguousManifestSelectionError",
    "MANIFEST_DIR",
    "ManifestEditError",
    "ManifestEditValidationError",
    "ManifestJobAlreadyExistsError",
    "ManifestJobNotFoundError",
    "MANIFEST_SUFFIXES",
    "ManifestMutationResult",
    "LoadedManifestDocument",
    "ManifestHashes",
    "ManifestLoadError",
    "ManifestNotFoundError",
    "ManifestParseError",
    "ProjectResolutionError",
    "RenderedWrapper",
    "RuntimePaths",
    "STATE_ENV_VAR",
    "ValidationMessage",
    "add_manifest_job",
    "attach_parsed_manifest",
    "build_error_payload",
    "build_manifest_hashes",
    "check_output_logged",
    "COMMAND_CONTRACTS",
    "CommandContract",
    "allowed_request_fields",
    "collapse_home_path",
    "CODEX_CONFIG_RELATIVE_PATH",
    "CODEX_HOOKS_RELATIVE_PATH",
    "CLAUDE_SETTINGS_RELATIVE_PATH",
    "ClaudeHookStatus",
    "configure_logging",
    "capture_session_end",
    "CodexHookStatus",
    "get_manifest_job",
    "default_backend_for_current_platform",
    "delete_project_state",
    "ensure_claude_hooks",
    "ensure_codex_hooks",
    "ensure_agent_hooks",
    "ensure_runtime_dirs",
    "ErrorDetail",
    "ErrorResponse",
    "get_logger",
    "get_command_contract",
    "HELP_PACKAGE",
    "HomeJobsSummary",
    "HomeResponse",
    "HookInstallResult",
    "HookStatusResult",
    "InspectResponse",
    "instrument_action",
    "inspect_agent_hooks",
    "inspect_claude_hooks",
    "inspect_codex_hooks",
    "JobListRow",
    "JobsListResponse",
    "JobsShowResponse",
    "list_manifest_jobs",
    "load_help_body",
    "load_project_manifest",
    "load_project_state",
    "map_apply_response",
    "map_error_response",
    "map_home_response",
    "map_inspect_response",
    "map_jobs_list_response",
    "map_jobs_mutation_response",
    "map_jobs_show_response",
    "map_plan_response",
    "map_prune_response",
    "map_status_response",
    "map_validation_response",
    "MutationResponse",
    "parse_fields_csv",
    "PayloadConvertible",
    "PlanChangeRow",
    "PlanResponse",
    "render_payload",
    "select_collection_fields",
    "render_wrapper",
    "render_help_text",
    "render_collection_response_toon",
    "render_list_response_toon",
    "render_nested_response_toon",
    "render_response_toon",
    "select_fields",
    "select_list_fields",
    "select_nested_fields",
    "resolve_manifest_path",
    "resolve_project_root",
    "resolve_project_state_dir",
    "resolve_project_state_path",
    "resolve_state_root",
    "resolve_runtime_paths",
    "runtime_log_paths_for_wrapper",
    "resolve_xcron_executable",
    "remove_manifest_job",
    "run_logged_subprocess",
    "set_manifest_job_enabled",
    "save_project_state",
    "StatusResponse",
    "StatusRow",
    "SummaryRow",
    "TOON_OPTIONS",
    "truncate_text",
    "normalize_for_toon",
    "render_toon",
    "update_manifest_job",
    "validate_schema",
    "validate_semantics",
    "validate_requested_fields",
    "ValidationSummaryResponse",
    "write_wrapper",
]
